name: Task
description: Create a task
title: "[TASK]"
projects: ["TheKing6488/19"] 
labels: [task]
assignees: ["TheKing6488"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Description
    validations:
      required: false