name: Task
description: Create a Task
title: "[TASK]"
labels: [task]
projects: ["Kopia Backup"] 
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Description
    validations:
      required: false