name: Task
description: Create a Task
title: "[TASK]"
projects: ["Kopia-Backup/19"] 
labels: [task]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Description
    validations:
      required: false