name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger bei Tags wie v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        runtime: [linux-x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish AOT
        run: |
          dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained true /p:PublishAot=true -o publish/

      - name: Package as tar.gz
        run: |
          cd publish
          tar -czf ../myapp-${{ github.ref_name }}-${{ matrix.runtime }}.tar.gz *

      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            myapp-*.tar.gz

  arch-pkg:
    runs-on: ubuntu-latest
    needs: build
    container: archlinux:latest

    steps:
      - name: Install build deps
        run: |
          pacman -Syu --noconfirm base-devel git

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build PKGBUILD
        run: |
          cd archpkg
          makepkg -fsri --noconfirm