name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Abhängigkeiten wiederherstellen
        working-directory: KopiaBackup/KopiaBackup.Console
        run: dotnet restore

      - name: Publish AOT
        working-directory: KopiaBackup/KopiaBackup.Console
        run: dotnet publish -c Release -o publish/

      - name: Package as tar.gz
        working-directory: KopiaBackup/KopiaBackup.Console/publish
        run:
          tar -czf $GITHUB_WORKSPACE/dockedbackup.tar.gz .

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dockedbackup.tar.gz
          path: dockedbackup.tar.gz

  arch-pkg:
    runs-on: ubuntu-latest
    needs: build
    container: archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup build‑Umgebung
        run: pacman -Syu --noconfirm --needed base-devel

      - name: Create builder user
        run: |
          useradd -m builder
          chown -R builder:builder $GITHUB_WORKSPACE

      - name: Download Source‑Tarball
        uses: actions/download-artifact@v4
        with:
          name: dockedbackup.tar.gz
          path: Build

      - name: Bau das Arch‑Paket
        working-directory: Build
        run: su builder -c "makepkg -f --skippgpcheck"

      - name: Upload Arch‑Paket
        uses: actions/upload-artifact@v4
        with:
          name: arch-pkg
          path: Build/*.pkg.tar.zst