name: Build and Release

on:
  push:
    branches: 
      - main

jobs:
  prepare:
    runs-on: ${{ matrix.build-on}}
    strategy:
      matrix:
        include:
        - rid:     linux-x64
          pkgarch: x86_64
          build-on: ubuntu-latest
        - rid:     linux-arm64
          pkgarch: aarch64
          build-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish for ${{ matrix.rid }}
        working-directory: KopiaBackup/KopiaBackup.Console
        run: dotnet publish -r ${{ matrix.rid }} -c Release --self-contained -p:PublishAot=true -o publish/
      
      - name: Copy Service & Scripts
        run: |
          cp Build/dockedbackup@.service KopiaBackup/KopiaBackup.Console/publish
          cp Build/dockedbackup.sh KopiaBackup/KopiaBackup.Console/publish
          cp Build/dockedbackup_install.sh KopiaBackup/KopiaBackup.Console/publish

      - name: Pack artifact
        working-directory: KopiaBackup/KopiaBackup.Console/publish
        run: tar -czf $GITHUB_WORKSPACE/dockedbackup-${{ matrix.pkgarch }}.tar.gz .

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.pkgarch }}
          path: dockedbackup-${{ matrix.pkgarch }}.tar.gz

  arch-pkg:
    runs-on: ${{ matrix.build-on }}
    strategy:
      matrix:
        include:
          - pkgarch: x86_64
            container: archlinux:latest
            build-on: ubuntu-latest
          - pkgarch: aarch64 
            container: menci/archlinuxarm:latest
            build-on: ubuntu-24.04-arm
    needs: prepare
    container: ${{matrix.container}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup build environment
        run: pacman -Syu --noconfirm --needed base-devel

      - name: Create builder user
        run: |
          useradd -m builder
          chown -R builder:builder $GITHUB_WORKSPACE

      - name: Download Source‑Tarball
        uses: actions/download-artifact@v4
        with:
          name: linux-${{ matrix.pkgarch }}
          path: Build

      - name: build arch package
        working-directory: Build
        run: su builder -c "makepkg -f --skippgpcheck"

      - name: Upload arch package
        uses: actions/upload-artifact@v4
        with:
          name: arch-${{ matrix.pkgarch }}
          path: Build/*.pkg.tar.zst
      

  release:
    needs: [ arch-pkg ]
    runs-on: ubuntu-latest
    steps:
      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dockedbackup-x86_64.tar.gz
            dockedbackup-aarch64.tar.gz
            dockedbackup-x86_64.pkg.tar.zst
            dockedbackup-aarch64.pkg.tar.zst
