name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Abhängigkeiten wiederherstellen
        working-directory: KopiaBackup/KopiaBackup.Console
        run: dotnet restore

      - name: Publish AOT
        working-directory: KopiaBackup/KopiaBackup.Console
        run: dotnet publish -c Release -o publish/

      - name: Package as tar.gz
        working-directory: KopiaBackup/KopiaBackup.Console/publish
        run:
          tar -czf $GITHUB_WORKSPACE/dockedbackup.tar.gz .

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish-folder
          path: dockedbackup.tar.gz

  # arch-pkg:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   container: archlinux:latest

  #   steps:
  #     - name: Install build deps
  #       run: |
  #         pacman -Syu --noconfirm base-devel git

  #     - name: Checkout Repo
  #       uses: actions/checkout@v3

  #     - name: Build PKGBUILD
  #       run: |
  #         cd archpkg
  #         makepkg -fsri --noconfirm